
import fs from 'fs';
import path from 'path';
import { exec } from 'child_process';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = path.join(__dirname, '../..');
const DATA_DIR = path.join(PROJECT_ROOT, 'src/data');
const SOUNDS_DIR = path.join(DATA_DIR, 'sounds');
const ASTERISK_CONF_DIR = '/etc/asterisk';
const ASTERISK_SOUNDS_DIR = '/var/lib/asterisk/sounds/en'; // Стандартный путь

// Создаем папки если их нет
if (!fs.existsSync(SOUNDS_DIR)) fs.mkdirSync(SOUNDS_DIR, { recursive: true });

function readJSON(filename) {
  const filePath = path.join(DATA_DIR, filename);
  if (!fs.existsSync(filePath)) return [];
  try {
    return JSON.parse(fs.readFileSync(filePath, 'utf8'));
  } catch (e) {
    return [];
  }
}

async function syncAsterisk() {
  console.log('🚀 [BRIDGE] Синхронизация с Asterisk...');

  const extensions = readJSON('extensions.json');
  const trunks = readJSON('trunks.json');
  const routes = readJSON('routes.json');
  const queues = readJSON('queues.json');
  const ivrs = readJSON('ivrs.json');

  // 1. Генерируем PJSIP Users
  let pjsipUsers = `; AUTO-GENERATED BY MIAC.SVYAZ\n`;
  extensions.forEach(ext => {
    pjsipUsers += `
[${ext.id}]
type=endpoint
context=from-internal
disallow=all
allow=ulaw,alaw,g722
auth=auth-${ext.id}
aors=${ext.id}
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
direct_media=no
identify_by=auth_username,username

[auth-${ext.id}]
type=auth
auth_type=userpass
password=${ext.secret}
username=${ext.id}

[${ext.id}]
type=aor
max_contacts=5
remove_existing=yes
`;
  });
  fs.writeFileSync(path.join(ASTERISK_CONF_DIR, 'pjsip_miac_users.conf'), pjsipUsers);

  // 2. Генерируем PJSIP Trunks + IDENTIFY (Важно для входящих!)
  let pjsipTrunks = `; AUTO-GENERATED BY MIAC.SVYAZ\n`;
  trunks.forEach(t => {
    pjsipTrunks += `
[trunk-${t.id}]
type=endpoint
context=from-trunk
disallow=all
allow=ulaw,alaw
outbound_auth=auth-${t.id}
aors=aor-${t.id}
identify_by=auth_username,username

[auth-${t.id}]
type=auth
auth_type=userpass
password=${t.password}
username=${t.user}

[aor-${t.id}]
type=aor
contact=sip:${t.host}:${t.port}

[registration-${t.id}]
type=registration
server_uri=sip:${t.host}:${t.port}
client_uri=sip:${t.user}@${t.host}:${t.port}
outbound_auth=auth-${t.id}
retry_interval=60

[identify-${t.id}]
type=identify
endpoint=trunk-${t.id}
match=${t.host}
`;
  });
  fs.writeFileSync(path.join(ASTERISK_CONF_DIR, 'pjsip_miac_trunks.conf'), pjsipTrunks);

  // 3. Генерируем Queues
  let queuesConf = `; AUTO-GENERATED BY MIAC.SVYAZ\n`;
  queues.forEach(q => {
    queuesConf += `
[${q.name}]
strategy=${q.strategy}
musicclass=${q.musicOnHoldClass || 'default'}
timeout=15
retry=5
wrapuptime=0
`;
    (q.members || []).forEach(m => {
      queuesConf += `member => PJSIP/${m}\n`;
    });
  });
  fs.writeFileSync(path.join(ASTERISK_CONF_DIR, 'queues_miac.conf'), queuesConf);

  // 4. Генерируем Dialplan (Extensions + Routes + IVR)
  let dialplan = `
[from-internal]
; Внутренняя связь
`;
  extensions.forEach(e => {
    dialplan += `exten => ${e.id},1,Dial(PJSIP/${e.id},30)\n`;
    dialplan += `same => n,Hangup()\n`;
  });

  // Исходящие маршруты
  routes.filter(r => r.type === 'outbound').forEach(r => {
    const trunkId = r.destination.split(':')[1];
    dialplan += `exten => _${r.pattern},1,NoOp(Outbound call via trunk-${trunkId})\n`;
    dialplan += `same => n,Dial(PJSIP/\${EXTEN}@trunk-${trunkId})\n`;
    dialplan += `same => n,Hangup()\n`;
  });

  // Контексты IVR
  ivrs.forEach(ivr => {
    dialplan += `\n[miac-ivr-${ivr.id}]\n`;
    dialplan += `exten => s,1,Answer()\n`;
    dialplan += `same => n,NoOp(Entering IVR: ${ivr.name})\n`;
    dialplan += `same => n,Background(${ivr.announcementFile})\n`;
    dialplan += `same => n,WaitExten(5)\n`;

    // Кнопки
    (ivr.digitMappings || []).forEach(m => {
      const [digit, type, target] = m.split(':');
      if (type === 'ext') dialplan += `exten => ${digit},1,Goto(from-internal,${target},1)\n`;
      if (type === 'queue') dialplan += `exten => ${digit},1,Queue(${target})\n`;
      if (type === 'ivr') dialplan += `exten => ${digit},1,Goto(miac-ivr-${target},s,1)\n`;
    });

    // Таймаут
    if (ivr.timeoutDestination) {
      const [tType, tTarget] = ivr.timeoutDestination.split(':');
      dialplan += `exten => t,1,NoOp(IVR Timeout, redirecting to ${tTarget})\n`;
      if (tType === 'Extension') dialplan += `same => n,Goto(from-internal,${tTarget},1)\n`;
      else if (tType === 'Queue') dialplan += `same => n,Queue(${tTarget})\n`;
      else dialplan += `same => n,Hangup()\n`;
    } else {
      dialplan += `exten => t,1,Hangup()\n`;
    }
    dialplan += `exten => i,1,Playback(invalid)\n`;
    dialplan += `same => n,Goto(s,1)\n`;
  });

  // Входящие маршруты
  dialplan += `\n[from-trunk]\n`;
  dialplan += `exten => s,1,NoOp(Incoming call on 's')\n`;
  const firstInbound = routes.find(r => r.type === 'inbound');
  if (firstInbound) {
    dialplan += `same => n,Goto(from-internal,${firstInbound.pattern},1)\n`;
  } else {
    dialplan += `same => n,Hangup()\n`;
  }

  routes.filter(r => r.type === 'inbound').forEach(r => {
    dialplan += `exten => ${r.pattern},1,NoOp(Incoming call to ${r.pattern})\n`;
    const [dType, dTarget] = r.destination.split(':');
    if (dType === 'Extension') dialplan += `same => n,Goto(from-internal,${dTarget},1)\n`;
    else if (dType === 'Queue') dialplan += `same => n,Queue(${dTarget})\n`;
    else if (dType === 'IVR') dialplan += `same => n,Goto(miac-ivr-${dTarget},s,1)\n`;
    dialplan += `same => n,Hangup()\n`;
  });

  fs.writeFileSync(path.join(ASTERISK_CONF_DIR, 'extensions_miac_dialplan.conf'), dialplan);

  // Синхронизация звуков
  if (fs.existsSync(SOUNDS_DIR)) {
    const files = fs.readdirSync(SOUNDS_DIR);
    files.forEach(f => {
      const src = path.join(SOUNDS_DIR, f);
      const dest = path.join(ASTERISK_SOUNDS_DIR, f);
      try {
        fs.copyFileSync(src, dest);
        fs.chmodSync(dest, 0o666);
      } catch (e) {
        console.error(`[BRIDGE] Error copying sound ${f}:`, e.message);
      }
    });
  }

  // Перезагрузка Asterisk
  exec('asterisk -rx "core reload"', (err) => {
    if (err) console.error('❌ [BRIDGE] Ошибка перезагрузки Asterisk:', err.message);
    else console.log('✅ [BRIDGE] Конфигурация обновлена и применена.');
  });
}

// Следим за изменениями
console.log('👀 [BRIDGE] Запуск наблюдателя за данными...');
fs.watch(DATA_DIR, (event, filename) => {
  if (filename && filename.endsWith('.json')) {
    syncAsterisk();
  }
});

// Первоначальный запуск
syncAsterisk();
