
import fs from 'fs';
import path from 'path';
import asteriskManager from 'asterisk-manager';
import dotenv from 'dotenv';

dotenv.config();

const DATA_DIR = path.join(process.cwd(), 'src/data');
const AST_DIR = '/etc/asterisk';

const FILES = {
  extensions: path.join(DATA_DIR, 'extensions.json'),
  trunks: path.join(DATA_DIR, 'trunks.json'),
  routes: path.join(DATA_DIR, 'routes.json'),
  queues: path.join(DATA_DIR, 'queues.json'),
  ivrs: path.join(DATA_DIR, 'ivrs.json'),
};

const AMI_CONFIG = {
  host: '127.0.0.1',
  port: 5038,
  user: 'miac',
  secret: 'MiacAMI2026',
};

const ami = new asteriskManager(AMI_CONFIG.port, AMI_CONFIG.host, AMI_CONFIG.user, AMI_CONFIG.secret, true);

function generatePJSIPUsers(extensions) {
  let conf = '; --- AUTO GENERATED BY MIAC.SVYAZ ---\n\n';
  extensions.forEach(ext => {
    conf += `[${ext.id}]\ntype=endpoint\ncontext=${ext.context || 'from-internal'}\ndisallow=all\nallow=ulaw,alaw,g722\nauth=${ext.id}\naors=${ext.id}\n\n`;
    conf += `[${ext.id}]\ntype=auth\nauth_type=userpass\nusername=${ext.id}\npassword=${ext.secret}\n\n`;
    conf += `[${ext.id}]\ntype=aor\nmax_contacts=1\nremove_existing=yes\n\n`;
  });
  return conf;
}

function generatePJSIPTrunks(trunks) {
  let conf = '; --- AUTO GENERATED TRUNKS ---\n\n';
  trunks.forEach(trunk => {
    conf += `[${trunk.id}]\ntype=registration\noutbound_auth=${trunk.id}\nserver_uri=sip:${trunk.host}:${trunk.port}\nclient_uri=sip:${trunk.user}@${trunk.host}:${trunk.port}\nretry_interval=60\n\n`;
    conf += `[${trunk.id}]\ntype=auth\nauth_type=userpass\nusername=${trunk.user}\npassword=${trunk.password}\n\n`;
    conf += `[${trunk.id}]\ntype=aor\ncontact=sip:${trunk.host}:${trunk.port}\n\n`;
    conf += `[${trunk.id}]\ntype=endpoint\ncontext=from-trunk\ndisallow=all\nallow=ulaw,alaw\noutbound_auth=${trunk.id}\naors=${trunk.id}\nfrom_user=${trunk.user}\n\n`;
    conf += `[${trunk.id}]\ntype=identify\nendpoint=${trunk.id}\nmatch=${trunk.host}\n\n`;
  });
  return conf;
}

function generateDialplan(extensions, routes, queues, ivrs) {
  let conf = '; --- AUTO GENERATED DIALPLAN ---\n\n';
  
  // Внутренняя связь
  conf += '[from-internal]\n';
  extensions.forEach(ext => {
    conf += `exten => ${ext.id},1,NoOp(Call to Extension ${ext.id})\n`;
    conf += ` same => n,Dial(PJSIP/${ext.id},30)\n`;
    conf += ` same => n,Hangup()\n`;
  });

  // Исходящие маршруты
  const outbound = routes.filter(r => r.type === 'outbound');
  outbound.forEach(route => {
    conf += `exten => _${route.pattern},1,NoOp(Outbound Call via ${route.destination})\n`;
    conf += ` same => n,Dial(PJSIP/\${EXTEN}@${route.destination})\n`;
    conf += ` same => n,Hangup()\n`;
  });

  // Входящие маршруты
  conf += '\n[from-trunk]\n';
  const inbound = routes.filter(r => r.type === 'inbound');
  inbound.forEach(route => {
    let dest = route.destination || '';
    let dialStr = '';
    if (dest.startsWith('Ext: ')) dialStr = `Dial(PJSIP/${dest.replace('Ext: ', '')},30)`;
    else if (dest.startsWith('Queue: ')) dialStr = `Queue(${dest.replace('Queue: ', '')})`;
    else if (dest.startsWith('IVR: ')) dialStr = `Goto(ivr-${dest.replace('IVR: ', '')},s,1)`;

    conf += `exten => ${route.pattern},1,NoOp(Inbound DID ${route.pattern})\n`;
    conf += ` same => n,${dialStr}\n`;
    conf += ` same => n,Hangup()\n`;
  });

  // IVR логика
  ivrs.forEach(ivr => {
    conf += `\n[ivr-${ivr.id}]\n`;
    conf += `exten => s,1,Answer()\n`;
    conf += ` same => n,Background(${ivr.announcementFile || 'demo-congrats'})\n`;
    conf += ` same => n,WaitExten(5)\n`;
    (ivr.digitMappings || []).forEach(m => {
      const parts = m.split(':'); // Format: digit:type:id
      if (parts.length === 3) {
        let cmd = parts[1] === 'ext' ? `Dial(PJSIP/${parts[2]},20)` : `Queue(${parts[2]})`;
        conf += `exten => ${parts[0]},1,${cmd}\n`;
      }
    });
    conf += `exten => t,1,Hangup()\n`;
    conf += `exten => i,1,Playback(invalid)\n same => n,Goto(s,1)\n`;
  });

  return conf;
}

async function sync() {
  console.log('🔄 [BRIDGE] Начало синхронизации...');
  try {
    const extensions = JSON.parse(fs.readFileSync(FILES.extensions, 'utf8') || '[]');
    const trunks = JSON.parse(fs.readFileSync(FILES.trunks, 'utf8') || '[]');
    const routes = JSON.parse(fs.readFileSync(FILES.routes, 'utf8') || '[]');
    const queues = JSON.parse(fs.readFileSync(FILES.queues, 'utf8') || '[]');
    const ivrs = JSON.parse(fs.readFileSync(FILES.ivrs, 'utf8') || '[]');

    fs.writeFileSync(path.join(AST_DIR, 'pjsip_miac_users.conf'), generatePJSIPUsers(extensions));
    fs.writeFileSync(path.join(AST_DIR, 'pjsip_miac_trunks.conf'), generatePJSIPTrunks(trunks));
    fs.writeFileSync(path.join(AST_DIR, 'extensions_miac_dialplan.conf'), generateDialplan(extensions, routes, queues, ivrs));

    console.log('✅ [BRIDGE] Файлы конфигурации обновлены.');

    const commands = ['module reload res_pjsip.so', 'dialplan reload'];
    for (const cmd of commands) {
      ami.action({ action: 'Command', command: cmd }, (err, res) => {
        if (!err) console.log(`🔄 [BRIDGE] Asterisk Command (${cmd}): OK`);
      });
    }
  } catch (e) {
    console.error('❌ [BRIDGE] Sync Error:', e.message);
  }
}

ami.on('managerevent', (evt) => {
  if (evt.event === 'PeerStatus' || evt.event === 'ContactStatus') {
    // В будущем тут можно ловить события регистрации
  }
});

console.log('🚀 [BRIDGE] Мост запущен...');
sync();
fs.watch(DATA_DIR, (evt, filename) => {
  if (filename.endsWith('.json')) sync();
});
