
/**
 * МИАЦ.СВЯЗЬ - Скрипт-мостик для AltLinux
 * Синхронизирует Firestore с локальными конфигами Asterisk
 * и обновляет статусы через AMI.
 */
import { initializeApp } from 'firebase/app';
import { getFirestore, collection, onSnapshot, doc, updateDoc } from 'firebase/firestore';
import amiManager from 'asterisk-manager';
import fs from 'fs';
import { exec } from 'child_process';
import { config } from 'dotenv';

config();

// Конфигурация Firebase (замените на свои значения из config.ts)
const firebaseConfig = {
  apiKey: "api-key",
  authDomain: "project-id.firebaseapp.com",
  projectId: "project-id",
  storageBucket: "project-id.appspot.com",
  messagingSenderId: "sender-id",
  appId: "app-id"
};

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

// Конфигурация AMI
const AMI_PORT = 5038;
const AMI_HOST = '127.0.0.1';
const AMI_USER = 'miac';
const AMI_PASS = 'MiacAMI2026';

const ami = new amiManager(AMI_PORT, AMI_HOST, AMI_USER, AMI_PASS, true);

console.log('🚀 [BRIDGE] Запуск системы синхронизации МИАЦ.СВЯЗЬ...');

// 1. Слушаем изменения Абонентов в Firestore и обновляем pjsip_miac_users.conf
onSnapshot(collection(db, 'extensions'), (snapshot) => {
  let configContent = '; --- AUTO GENERATED BY MIAC-BRIDGE ---\n\n';
  
  snapshot.forEach((doc) => {
    const ext = doc.data();
    configContent += `[${ext.id}]\ntype=endpoint\ncontext=${ext.context || 'from-internal'}\ndisallow=all\nallow=ulaw,alaw\nauth=auth${ext.id}\naors=${ext.id}\ntransport=transport-udp\n\n`;
    configContent += `[auth${ext.id}]\ntype=auth\nauth_type=userpass\nusername=${ext.id}\npassword=${ext.secret}\n\n`;
    configContent += `[${ext.id}]\ntype=aor\nmax_contacts=1\n\n`;
  });

  try {
    fs.writeFileSync('/etc/asterisk/pjsip_miac_users.conf', configContent);
    console.log('📝 [BRIDGE] Конфигурация PJSIP обновлена. Перезагрузка Asterisk...');
    exec('asterisk -rx "pjsip reload"', (err) => {
      if (err) console.error('❌ [ERROR] Ошибка перезагрузки PJSIP:', err);
    });
  } catch (e) {
    console.error('❌ [ERROR] Нет доступа к записи в /etc/asterisk/. Запустите от root или проверьте права.');
  }
});

// 2. Слушаем события AMI и обновляем статусы в Firestore
ami.on('peerstatus', (evt) => {
  const channel = evt.peer || '';
  const status = evt.peerstatus === 'Registered' ? 'online' : 'offline';
  const extId = channel.split('/')[1] || channel;

  console.log(`📡 [AMI] Изменение статуса: ${extId} -> ${status}`);
  
  // Обновляем статус в Firestore, если абонент существует
  const extRef = doc(db, 'extensions', extId);
  updateDoc(extRef, { status }).catch(() => {
    // Абонент может отсутствовать в базе, если это сторонний транк
  });
});

ami.on('error', (err) => {
  console.error('❌ [AMI ERROR]', err);
});

process.on('SIGINT', () => {
  ami.disconnect();
  process.exit();
});
